import { UserDto } from './main.dto';
import { PickType } from '@nestjs/mapped-types';

export class PostUserDto extends PickType(UserDto, [
	'role',
	'first_name',
	'last_name',
	'date_of_birth',
	'pesel',
	'email',
	'phone_number',
	'street',
	'city',
	'postal_code',
	'password',
	'id_card_number',
	'id_card_issue',
	'id_card_expiry',
	'profession',
	'monthly_net_income',
	'main_income_sources',
] as const) {}

export const PostUserRolesDto = {
	ADMIN: [
		'role',
		'first_name',
		'last_name',
		'date_of_birth',
		'pesel',
		'email',
		'phone_number',
		'street',
		'city',
		'postal_code',
		'password',
		'id_card_number',
		'id_card_issue',
		'id_card_expiry',
		'profession',
		'monthly_net_income',
		'main_income_sources',
	] as const,
	EMPLOYEE: [
		'first_name',
		'last_name',
		'date_of_birth',
		'pesel',
		'email',
		'phone_number',
		'street',
		'city',
		'postal_code',
		'password',
		'id_card_number',
		'id_card_issue',
		'id_card_expiry',
		'profession',
		'monthly_net_income',
		'main_income_sources',
	] as const,
} as const;
